//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLoggerMonitorApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string serialComName {
            get {
                return ((string)(this["serialComName"]));
            }
            set {
                this["serialComName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string serialSpeedRate {
            get {
                return ((string)(this["serialSpeedRate"]));
            }
            set {
                this["serialSpeedRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string serialParity {
            get {
                return ((string)(this["serialParity"]));
            }
            set {
                this["serialParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8 bits")]
        public string serialDataBits {
            get {
                return ((string)(this["serialDataBits"]));
            }
            set {
                this["serialDataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1 bits")]
        public string serialStopBits {
            get {
                return ((string)(this["serialStopBits"]));
            }
            set {
                this["serialStopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string serialFlow {
            get {
                return ((string)(this["serialFlow"]));
            }
            set {
                this["serialFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UTF-8")]
        public string serialEncode {
            get {
                return ((string)(this["serialEncode"]));
            }
            set {
                this["serialEncode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\r\\n")]
        public string serialEnterCode {
            get {
                return ((string)(this["serialEnterCode"]));
            }
            set {
                this["serialEnterCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"時間,経過時間,電圧[V],バッテリ電流[A],ソーラー電流[A],モータ電流[A],バッテリ電力[W],ソーラー電力[W],モータ電力[W],バッテリ積算電力[Wh],ソーラー積算電力[Wh],モータ積算電力[Wh],速度[km/h],モータ温度[℃],残量[Wh],合計[V],最小[V],最大[V],距離[km],GPS速度[km/h],MPPT1-1,MPPT1-2,MPPT1-3,MPPT1-4,MPPT1-5,MPPT2-1,MPPT2-2,MPPT2-3,MPPT2-4,MPPT2-5,MPPT2-6,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16")]
        public string dataAryColName {
            get {
                return ((string)(this["dataAryColName"]));
            }
            set {
                this["dataAryColName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False")]
        public string dataAryColShow {
            get {
                return ((string)(this["dataAryColShow"]));
            }
            set {
                this["dataAryColShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int serialDataNum {
            get {
                return ((int)(this["serialDataNum"]));
            }
            set {
                this["serialDataNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int chartSettings_x {
            get {
                return ((int)(this["chartSettings_x"]));
            }
            set {
                this["chartSettings_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string chartSettings_y {
            get {
                return ((string)(this["chartSettings_y"]));
            }
            set {
                this["chartSettings_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2,14")]
        public string chartSettings_y2 {
            get {
                return ((string)(this["chartSettings_y2"]));
            }
            set {
                this["chartSettings_y2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-21600")]
        public int xmin {
            get {
                return ((int)(this["xmin"]));
            }
            set {
                this["xmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21600")]
        public int xmax {
            get {
                return ((int)(this["xmax"]));
            }
            set {
                this["xmax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ymin {
            get {
                return ((int)(this["ymin"]));
            }
            set {
                this["ymin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6000")]
        public int ymax {
            get {
                return ((int)(this["ymax"]));
            }
            set {
                this["ymax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int y2min {
            get {
                return ((int)(this["y2min"]));
            }
            set {
                this["y2min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int y2max {
            get {
                return ((int)(this["y2max"]));
            }
            set {
                this["y2max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int solarPowerNum {
            get {
                return ((int)(this["solarPowerNum"]));
            }
            set {
                this["solarPowerNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int solarPowerWhNum {
            get {
                return ((int)(this["solarPowerWhNum"]));
            }
            set {
                this["solarPowerWhNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int motorPowerWhNum {
            get {
                return ((int)(this["motorPowerWhNum"]));
            }
            set {
                this["motorPowerWhNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int speedNum {
            get {
                return ((int)(this["speedNum"]));
            }
            set {
                this["speedNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int motorPowerNum {
            get {
                return ((int)(this["motorPowerNum"]));
            }
            set {
                this["motorPowerNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int serialCountNum {
            get {
                return ((int)(this["serialCountNum"]));
            }
            set {
                this["serialCountNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double carWeight {
            get {
                return ((double)(this["carWeight"]));
            }
            set {
                this["carWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public double motorEff {
            get {
                return ((double)(this["motorEff"]));
            }
            set {
                this["motorEff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public int xThickness {
            get {
                return ((int)(this["xThickness"]));
            }
            set {
                this["xThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int yThickness {
            get {
                return ((int)(this["yThickness"]));
            }
            set {
                this["yThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int y2Thickness {
            get {
                return ((int)(this["y2Thickness"]));
            }
            set {
                this["y2Thickness"] = value;
            }
        }
    }
}
